show_downloads: true
title: vth
description: Physics simulator written in Go
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
logo: /data/icon.png
url: "https://mdmackint.xyz"