# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Install dependencies
      run: sudo apt install -y gcc libc6-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev libasound2-dev pkg-config

    - name: Build binaries for Windows and Linux
      run: |
        GOOS=windows GOARCH=amd64 go build -v -o vth-windows-amd64.exe
        GOOS=linux GOARCH=amd64 go build -v -o vth-linux-amd64

    - name: Upload compiled Windows binary
      uses: actions/upload-artifact@v4
      with:
        name: vth-windows-amd64.exe
        path: vth-windows-amd64.exe
        
    - name: Upload compiled Linux binary
      uses: actions/upload-artifact@v4
      with:
        name: vth-linux-amd64
        path: vth-linux-amd64
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetch Windows binary
        uses: actions/download-artifact@v4
        with:
          name: vth-windows-amd64.exe
          path: vth-windows-amd64.exe
      - name: Fetch Linux binary
        uses: actions/download-artifact@v4
        with:
          name: vth-linux-amd64
          path: vth-linux-amd64
      - name: Release if tagged
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref,'refs/tags/')
        with:
          files: |
            vth-linux-amd64
            vth-windows-amd64.exe
